name: Build (deploy later)
# update
on:
  push:
    branches: [sub, main2, main]
  pull_request:
    branches: [sub, main2, main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Check DATABASE_URL directly
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          if [[ -z "$DATABASE_URL" ]]; then
            echo "DATABASE_URL is missing"
          else
            echo "DATABASE_URL starts with: ${DATABASE_URL:0:10}"
          fi


      - name: Install dependencies
        run: |
          cd client
          npm install --legacy-peer-deps --verbose
          npm install --save-dev jest jest-environment-jsdom @testing-library/jest-dom @testing-library/react --legacy-peer-deps --verbose

      - name: Create .env file for Prisma
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> client/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> client/.env
          echo "PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }}" >> client/.env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> client/.env

      - name: Run unit tests
        env:
          CI: true
        run: |
          cd client
          npm test --verbose

      - name: Test Perplexity API connection
        run: cd client && npm run test:api

  build:
    needs: test
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      
      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Create .env file for Prisma
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> client/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> client/.env
          echo "PERPLEXITY_API_KEY=${{ secrets.PERPLEXITY_API_KEY }}" >> client/.env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> client/.env
    
      
      - name: Build the project
        run: cd client && npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: client/.next/

#Uncomment and configure this section during deployment


# deploy:
#   needs: build
#   if: github.ref == 'refs/heads/main'
#   runs-on: ubuntu-latest
#   
#   steps:
#   - uses: actions/checkout@v3
#   
#   - name: Download build artifacts
#     uses: actions/download-artifact@v4
#     with:
#       name: build-files
#       path: .next/
#   
#   - name: Set up Node.js
#     uses: actions/setup-node@v3
#     with:
#       node-version: '18'
#   
#   - name: Install dependencies
#     run: npm ci
#   
#   # Example deployment to Vercel, adjust as needed
#   - name: Deploy to Vercel
#     uses: amondnet/vercel-action@v20
#     with:
#       vercel-token: ${{ secrets.VERCEL_TOKEN }}
#       vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#       vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
#       vercel-args: '--prod'
